import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  aPPSidebar: [{ type: 'autogenerated', dirName: 'APP-Docs' }],
  webSidebar: [{ type: 'autogenerated', dirName: 'Web-Docs' }],
  backendSidebar: [{ type: 'autogenerated', dirName: 'Backend-Docs' }],
  

 
};

export default sidebars;
